### ISSUE TITLE
Are you an owner of gmail.com :D ?

### ISSUE THREAD

**Issue by swojtczak** [ArturGrochowski/SpeedTicTacToe#3]
Change the package tree name to your own like: com. ArturGrochowski 

https://github.com/ArturGrochowski/SpeedTicTacToe/blob/b94cd987459c40594cfc6338193c898678729831/app/src/main/java/com/gmail/speedtictactoe/MainActivity.java#L1

**Comment by arturgrochowski** [comment]
you never know ;D

**Comment by arturgrochowski** [comment]
done! :)

**Comment by swojtczak** [comment]
OK
