### ISSUE TITLE
Use only english names

### ISSUE THREAD

**Issue by swojtczak** [ArturGrochowski/SpeedTicTacToe#5]
As mentioned in title. No 'kwadrat's no 'trojkat' allowed. 

https://github.com/ArturGrochowski/SpeedTicTacToe/blob/b94cd987459c40594cfc6338193c898678729831/app/src/main/java/com/gmail/speedtictactoe/PlayGrid.java#L349

**Comment by arturgrochowski** [comment]
OK. Done :)
